// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFizenoRAqKvNHtS7DOloz-Hnlkp88FqU',
    appId: '1:957376514358:web:d65d5e4560c3225d274b97',
    messagingSenderId: '957376514358',
    projectId: 'flutter-leboncoin',
    authDomain: 'flutter-leboncoin.firebaseapp.com',
    storageBucket: 'flutter-leboncoin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa1MZK-3D32RdLDt6hZDwlHS5Q63yjrSg',
    appId: '1:957376514358:android:2b90a4f09700712d274b97',
    messagingSenderId: '957376514358',
    projectId: 'flutter-leboncoin',
    storageBucket: 'flutter-leboncoin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5UTs6CpqoECf3rSo3SWI6morIjcpd74',
    appId: '1:957376514358:ios:4cb935dfd4f6f949274b97',
    messagingSenderId: '957376514358',
    projectId: 'flutter-leboncoin',
    storageBucket: 'flutter-leboncoin.appspot.com',
    iosClientId: '957376514358-hmni6b34bcnppg60kek8nlnj2dihorgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCloneBonCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi5UTs6CpqoECf3rSo3SWI6morIjcpd74',
    appId: '1:957376514358:ios:4cb935dfd4f6f949274b97',
    messagingSenderId: '957376514358',
    projectId: 'flutter-leboncoin',
    storageBucket: 'flutter-leboncoin.appspot.com',
    iosClientId: '957376514358-hmni6b34bcnppg60kek8nlnj2dihorgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCloneBonCoin',
  );
}
